btnAdd.text=Add Selected (GM)
btnOrder.text=Order Selected
cost.heading=Cost
inUse.heading=In use
intransit.heading=In Transit
planned.heading=Plan To Order
part.heading=Part
stored.heading=Stored
storedTonnage.heading=Tonnage
includeInOrder.heading=Include?

