add.text=Add (GM)
addInBulk.text=Add in Bulk (GM)
buy.text=Buy
buyInBulk.text=Buy in Bulk
cost.heading=Cost Per
inUse.heading=# In Use
transit.heading=# In Transit
ordered.heading=# Ordered
part.heading=Part Name
stored.heading=Stored
storedTonnage.heading=Tonnage
